I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 404, in script
    alec "hey [player_name] - not really"
Exception: Sayer 'alec' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 404, in script
    alec "hey [player_name] - not really"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'alec' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Practicing Safe Sex(t): The Game 1.0
Tue Mar 15 20:33:52 2022
